### ISSUE TITLE
Unexpected module_genes outpit for mouse

### ISSUE THREAD

**Issue by OlgaVT** [Shamir-Lab/domino_web#11]
Hi,

thank you for the great tool. I am currently using a web version to analyze mouse data with a preloaded network. As an active genes set I am using a list of mouse genes but in the output (module_genes.txt) I receive a list of human genes. I think for now I will try the python package, however, such an output looks unexpected. Is it possible to change? Or am I doing something wrong? Thank you!

**Comment by hag007** [comment]
Hi OlgaVT,

Thanks for using DOMINO web!
Could you please upload/send the exact input you ran your analysis with, and the zip output you got? 
Also, which preloaded network did you use?

**Comment by OlgaVT** [comment]
Hi,

thank you! I did not check the corresponding paper - now the output makes total sense. However, I find the sentence 'For preloaded networks, only human and mouse are supported' in the http://domino.cs.tau.ac.il/file-upload page a bit misleading without reading the paper - I would expect here the analysis fully performed on the mouse active genes/network. It would be helpful if the conversion to human orthologs is also mentioned there.
