### ISSUE TITLE
DOMINO server down

### ISSUE THREAD

**Issue by MOohTus** [Shamir-Lab/domino_web#12]
Hello, 

I created a tool that is performing active module identification using DOMINO server. 
But the DOMINO web page seems to be down, and the server isn't accessible neither. 
Do you know if it will be again available soon ?

Thank you a lot for your work, 
Best, 

Morgane

**Comment by hag007** [comment]
Hi Morgane,

Unfortunately, there are some heavy maintenance procedure on the servers where DOMINO is deployed.
I hope this issue will be solved in the next few days.
Will keep you posted

**Comment by hag007** [comment]
DOMINO server is back online!
